### ISSUE TITLE
What's handled?

### ISSUE THREAD

**Issue by TPS** [Xuf3r/metapurge-rs#13]
@Xuf3r Is there any documentation on what file formats are cleaned?  At least a list of extensions/MIME types/&c?

**Comment by Xuf3r** [comment]
Hello! Updated the readme with supported extensions.
Unfortunately i simply parse the extension names and the tool doesn't interact with web, so it doesn't *directly* support MIME.

**Comment by TPS** [comment]
@Xuf3r Thanks very much 🙇🏾‍♂️
